<template>
	<div id="about-container">
		<div id="bread">Data Sources</div>
		<div id="separator"></div>
		<div id="title">Data for Decision making uses some of the best real time data sources available.</div>
		<p>Disaster data disaster severity and extent is sourced from <a href="#">gdacs</a>.</p>
		<p>It’s a joint initiative of the European Union and the United Nations and is provided in real time by GDACs.</p>
		<p>Baseline population data is provided by the <a href="#">Facebook/ciesin Columbia University Earth Scientists centre</a>.</p>
		<ul>
			<li>Based on the 2010 census data from <a href="#">BPS</a> (the national statistics office)</li>
			<li>Overlayed with high resolution satellite imagery</li>
			<li>Projected using the independently varified <a href="#">Facebook/ciesin machine learning algorithm</a></li>
			<li>Displacement data provided by <a href="#">Facebook Geo Insights</a></li>
			<li>Generated by 120 million Facebook users who have opted in to the geo insights program</li>
		</ul>
	</div>
</template>

<script>
export default {
	name: 'about',
	components: { },
	data: () => ({

	}),
	computed: {

	},
	methods: {

	},
	mounted: function() {

	}
}
</script>

